### ISSUE TITLE
PRACTICA

### ISSUE THREAD

**Issue by Erick-3as** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Erick-3as#1]
[OPERACIONES BASICAS ERICK.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-Erick-3as/files/7166223/OPERACIONES.BASICAS.ERICK.pdf)

**Comment by JulioCGz** [comment]
20% de calificación

**Comment by josealfredo79** [comment]
Bien hecho y revisado
